name: 'API Gateway Deployer Action'
description: 'Custom Action para desplegar  api gateway contra servicios EKS que usan NLB y API Link'
inputs:

  swagger_path:
    description: Ubicación del archivo Swagger
    default: apidef/apidef-swagger.yaml
    required: false

  service_version:
    description: Version del container
    required: true

  stage_name:
    description: Identificador de stage_name
    required: false
    default: v1

  eks_cluster_name:
    description: Cluster sobre el cual se relacionará api gateway
    required: true

  service_name:
    description: Nombre del servicio o imagen
    required: true

  project: 
    description: Identificador del proyecto
    required: true

  authorizer_function:
    description: Nombre de la funcion lambda authorizer
    required: true

  authorizer_role_name:
    description: Nombre del rol para ejecución de authorizer
    required: true

  environment:
    description: Ambiente de despliegue de la api
    required: true

  region:
    description: Region AWS
    default: us-east-1
    required: false

  aws_access_key_id:
    description: access key
    required: false

  aws_secret_access_key:
    description: Secret access key
    required: false

  cors_domain:
    description: CORS Domain allowed
    required: false
    default: "*"
    
  namespace:
    description: Namespace objetivo
    required: false
    default: "cpat"


  





runs:
  using: 'docker'
  image: 'Dockerfile'
